name: pull-request

on: [pull_request]

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # https://www.chromatic.com/docs/github-actions#support-for-codeactionscheckoutv2code-and-above
      - run: npm ci

      # GitHub ActionsでResource not accessible by integrationが出た時の対処法
      # https://zenn.dev/tatsugon/articles/github-actions-permission-error
      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: "./"
          fail_on_error: true
